use scott;

SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

-- NATURAL JOIN : DEPTNO를 기준으로 자동 등가 조인
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
FROM EMP E NATURAL JOIN DEPT D;

# LEFT OUTER JOIN
# 왼쪽 테이블을 기준으로, 오른쪽 데이터 존재 여부와 상관없이 모두 출력.

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2
                            ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

# RIGHT OUTER JOIN
# 오른쪽 테이블을 기준으로, 왼쪽 데이터와 상관없이 모두 출력.

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2
                             ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

# LEFT JOIN과 RIGHT JOIN을 결합한 것. 양쪽 모두 짝이 없어도 출력한다.
# ⚠️ MySQL은 FULL OUTER JOIN을 직접 지원하지 않는다. LEFT JOIN과 RIGHT JOIN 결과를 UNION으로 합쳐 같은 효과를 낸다.

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
UNION
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY EMPNO;

# 실습) JOIN ~ USING 키워드를 사용할 것. 급여가 3000 이상이며, 직속상관이 반드시 있는 사원을 출력하시오.
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL >= 3000 AND E.MGR IS NOT NULL
ORDER BY E.EMPNO;