use scott;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;

# UNION : 합집합 (중복 제거)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;

# UNION ALL : 합집합 (중복 포함)
-- UNION ALL : 중복 포함 → 두 번 모두 출력
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

# INTERSECT : 교집합 (중복 제거)
# ℹ️ INTERSECT는 MySQL 8.0.31 이상에서 지원한다. 그 이전 버전에서는 INNER JOIN이나 IN / EXISTS로 교집합을 구현해야 한다.
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- INTERSECT 미지원 버전에서의 대체 (IN 사용 예)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
  AND EMPNO IN (SELECT EMPNO FROM EMP);

# EXCEPT : 차집합 (중복 제거)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
EXCEPT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;